package com.adingrt.cliente.cocina;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Adin Rubio
 */
public class TicketDePedidoPanel extends javax.swing.JPanel {

    public JLabel getLblNumeroPedido() {
        return lblNumeroPedido;
    }

    public JPanel getPanelPedido() {
        return panelPedido;
    }

    private List<JPanel> items;
    private int indice;
    
    /**
     * Creates new form TicketPedido2
     */
    public TicketDePedidoPanel() {
        initComponents();
        items = new ArrayList<>();
        indice = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNoPedido = new javax.swing.JPanel();
        lblNumeroPedido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelPedido = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(new java.awt.BorderLayout());

        panelNoPedido.setBackground(new java.awt.Color(51, 51, 51));
        panelNoPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelNoPedido.setForeground(new java.awt.Color(255, 255, 255));
        panelNoPedido.setMaximumSize(new java.awt.Dimension(0, 0));
        panelNoPedido.setPreferredSize(new java.awt.Dimension(30, 30));
        panelNoPedido.setLayout(new java.awt.GridLayout(1, 0));

        lblNumeroPedido.setBackground(new java.awt.Color(51, 51, 51));
        lblNumeroPedido.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroPedido.setText("PEDIDO NO.");
        panelNoPedido.add(lblNumeroPedido);

        add(panelNoPedido, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        panelPedido.setBackground(new java.awt.Color(204, 204, 204));
        panelPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelPedido.setForeground(new java.awt.Color(0, 0, 0));
        panelPedido.setMaximumSize(new java.awt.Dimension(0, 0));
        panelPedido.setPreferredSize(new java.awt.Dimension(50, 50));
        panelPedido.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(panelPedido);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("ENTREGAR");
        add(jButton1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumeroPedido;
    private javax.swing.JPanel panelNoPedido;
    private javax.swing.JPanel panelPedido;
    // End of variables declaration//GEN-END:variables
}
